// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  fragrance_list: dynamic(() => import("./FragranceList")),
  hero: dynamic(() => import("./Hero")),
  product_ferature: dynamic(() => import("./ProductFeature")),
  scroll_text: dynamic(() => import("./ScrollText")),
  video: dynamic(() => import("./Video")),
};
